version: '3'

services:
  nginx:
    image: nginx
    networks:
      - local
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - gitlab
      - jenkins
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/conf.d/gitlab.conf:/etc/nginx/conf.d/gitlab.conf:ro
      - ./nginx/conf.d/jenkins.conf:/etc/nginx/conf.d/jenkins.conf:ro

  postgresql:
    restart: unless-stopped
    image: postgres:9.6
    networks:
      - local
    container_name: postgres
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql:Z
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_USER=user
      - DB_PASS=user
      - DB_NAME="gitlab_db jenkins_db"

  gitlab:
    restart: unless-stopped
    image: gitlab/gitlab-ce
    networks:
      - local
    container_name: gitlab
    hostname: gitlab.local
    depends_on:
      - postgresql
    environment:
      - DB_ADAPTER=postgresql
      - DB_HOST=postgres
      - DB_NAME=gitlab_db
      - DB_USER=user
      - DB_PASS=user
    volumes:
      - gitlab_etc:/etc/gitlab:Z
      - gitlab_opt:/var/opt/gitlab:Z
      - gitlab_log:/var/log/gitlab:Z

  jenkins:
    restart: unless-stopped
    image: jenkins/jenkins
    networks:
      - local
    container_name: jenkins
    hostname: jenkins.local
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro

volumes:
  jenkins_home:
  gitlab_etc:
  gitlab_opt:
  gitlab_log:

networks:
  local:
    driver: bridge
